Update Falcon Sensor Dockerfile
CrowdStrike/Dockerfiles pull request #11
Opened 2021-01-07 19:05 UTC by redhatrises

- Clean up single line invocations to be multi-line
- Parameterize the rpm name for sensor install
- Update Readme

2021-01-07 23:12 UTC, shawndwells requested changes
Cannot use podman by default as it's a Linux only tool. Requires Linux virtual machines and other things to run on common platforms like OSX. Ref:

https://podman.io/getting-started/installation
```
Podman is a tool for running Linux containers. **You can do this from a MacOS desktop as long as you have access to a linux box either running inside of a VM on the host, or available via the network**. You need to install the remote client and then setup ssh connection information.
```

2021-01-07 23:12 UTC, shawndwells commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container is easier rather than hard-coding your CID and creating a new container image.
Give a full example. What config file do we put ``-e FALCONCTL_OPT_CID`` into? Is this a command line argument? To what command?

2021-01-07 23:25 UTC, redhatrises commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container is easier rather than hard-coding your CID and creating a new container image.
This is referenced from below... add wording to state as such.

2021-01-07 23:26 UTC, redhatrises commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container is easier rather than hard-coding your CID and creating a new container image.
> Cannot use podman by default as it's a Linux only tool. Requires Linux virtual machines and other things to run on common platforms like OSX. Ref:
> 
> https://podman.io/getting-started/installation
> 
> ```
> Podman is a tool for running Linux containers. **You can do this from a MacOS desktop as long as you have access to a linux box either running inside of a VM on the host, or available via the network**. You need to install the remote client and then setup ssh connection information.
> ```

Right... habit... fixed.

2021-01-08 01:23 UTC, shawndwells requested changes

2021-01-08 01:23 UTC, shawndwells commented on Dockerfile
> -USER root
This was intentional since we're using base images that aren't generated ourselves. Need to insulate against upstream changes. It's also nice to explicitly remind users we need the root container.

2021-01-08 01:23 UTC, shawndwells commented on Dockerfile
> +    libnl3 net-tools zip openssl hostname iproute /tmp/falcon-sensor.rpm && \
Why switch from ``libnl`` to ``libnl3``?

2021-01-08 01:23 UTC, shawndwells commented on Dockerfile
> +    libnl3 net-tools zip openssl hostname iproute /tmp/falcon-sensor.rpm && \
Meaning was this tested?

2021-01-08 01:23 UTC, shawndwells commented on README.md
> +* Install `docker` or `podman` if not already present on the build host. The following instructions use `docker` commands, but `podman` commands work just fine as well.
```suggestion
* Install `docker` or `podman` if not already present on the build host. The following instructions use `docker` commands, but `podman` commands [work just fine as well](https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/).
```

2021-01-08 01:23 UTC, shawndwells commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container detached (when the `-d` argument is used. See below) is easier rather than hard-coding your CID and creating a ne
```suggestion
This could be replaced with a sed one-liner such as ``sed -i 's/YOURCID/xyz/r' entrypoint.sh``. *Try not to commit your CID to your Git repo!*
  
Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container detached (when the `-d` argument is used. See below) is easier rather than hard-coding your CID and creating a new container image.
```

2021-01-08 01:23 UTC, shawndwells commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container detached (when the `-d` argument is used. See below) is easier rather than hard-coding your CID and creating a ne
The language around `-e FALCONCTL` does not state how/where/when this argument should be passed. Examples are needed for this.

2021-01-08 01:23 UTC, shawndwells commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container detached (when the `-d` argument is used. See below) is easier rather than hard-coding your CID and creating a ne
(eg did you intend to also update the ``docker build`` below?)

2021-01-08 15:52 UTC, redhatrises commented on Dockerfile
> +    libnl3 net-tools zip openssl hostname iproute /tmp/falcon-sensor.rpm && \
In RHEL8, it's libnl3:

For an 8.1 image:

```
Dependencies resolved.
=====================================================================================================================================
 Package                                        Architecture   Version                                 Repository               Size
=====================================================================================================================================
Upgrading:
 yum                                            noarch         4.2.23-4.el8                            ubi-8-baseos            192 k
...
 libnl3                                         x86_64         3.5.0-1.el8                             ubi-8-baseos            320 k
...
```

And for latest:

```
Last metadata expiration check: 0:00:05 ago on Fri Jan  8 15:45:20 2021.
No match for argument: libnl
Error: Unable to find a match: libnl
Error: error building at STEP "RUN yum -y update &&     yum -y install --disablerepo=*     --enablerepo=ubi-8-appstream     --enablerepo=ubi-8-baseos     libnl net-tools zip openssl hostname iproute /tmp/falcon-sensor.rpm &&     yum -y clean all && rm -rf /var/cache/yum &&     rm -f /tmp/falcon-sensor.rpm": error while running runtime: exit status 1
```

2021-01-08 16:12 UTC, redhatrises commented on README.md
> +  Alternatively, using `-e FALCONCTL_OPT_CID=<<YOUR CID>>` when running the container detached (when the `-d` argument is used. See below) is easier rather than hard-coding your CID and creating a ne
> The language around `-e FALCONCTL` does not state how/where/when this argument should be passed. Examples are needed for this.

@shawndwells this is mentioned starting in lines 55 and 76 of the updated README. Maybe the Readme structure needs to be reworked?

> (eg did you intend to also update the `docker build` below?)

I did. This is mentioned in line 17. The RPM is now paramaterized.

2021-01-08 16:31 UTC, redhatrises commented on Dockerfile
> -USER root
Okay.... re-added.

2021-01-22 15:49 UTC, shawndwells approved these changes

2021-01-22 15:49 UTC, merged